name: SwedishChessClock
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 15.0
targets:
  SwedishChessClock:
    type: application
    platform: iOS
    sources:
      - SwedishChessClock
    settings:
      base:
        INFOPLIST_FILE: SwedishChessClock/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.SwedishChessClock
    info:
      path: SwedishChessClock/Info.plist
      properties:
        CFBundleDisplayName: Swedish Chess Clock
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight 